### PR TITLE
Countdown template

### PR DESCRIPTION
**Pull request by JesseyH**

### CODE REVIEW

**Comment by JesseyH** [comment]
Bare Bones display of the timer countdown:
image

Red text are editable from variables in the view.py file:
image

the variables are called in the html template by surrounding the variable name with `{{ }}`:
image

**Comment by JesseyH** [comment]
FYI, to view the page run the server and go to [http://127.0.0.1:8000/timer/](http://127.0.0.1:8000/timer/)

**Comment by JesseyH** [comment]
@AlexCHLo I think I think this PR completes you task: #38 
Can you review and confirm my implementation is correct?

**Review by AlexCHLo — APPROVED** [review]
It looks more or less like what I have done with a placeholder template. Looks good though.

**Review by erick576 — APPROVED** [review]

**Comment by erick576** [comment]
Changes Looks good

**Review by digengill — APPROVED** [review]

**Pull request merged**
