### PR TITLE
Machine overview and 

### PR DESCRIPTION
**Pull request by JesseyH**
**New Features:**
All the pages are created and connected
- #52
- #53 
- #21

Countdown and timer page are based on each machine. Connected the model and the view so that time left on the countdown page persists when the page is reloaded.
- #60

**Restrictions:**
- I set a default user (User with id 1)
- I made the user only be able to set the remaining time on their account to the machine.
- User can use multiple machines.

**Instructions on setup and testing:**
**setup:**
1. Run: python3 manage.py runserver
2. Go to http://127.0.0.1:8000/admin
3. Create as many Machines as wanted, add at least one user (We only use one for now) make sure the time on the User > 0 make around 30 seconds to be able to quickly test everything

**testing:** 
1. Go to http://127.0.0.1:8000/machines
   - All the machines you selected should appear
2. Select a machine
   - you should be redirected to the set timer page
   - the time you set for the first user should show at the top
3. Click the submit button
   - you should be redirected to the countdown page the time should start from the time you selected 
5. Try reloading the page 
   - The timer should still be accurate
6. Try visiting other pages to see if everything makes sense
7.  When the timer ends the time should be reflected in the user model.

### CODE REVIEW

**Comment by JesseyH** [comment]
Also added login path to urls.py

**Comment by erick576** [comment]
@JesseyH @ChandlerCabrera Could you possibly fix the commit history on this branch with your changes? As it is right now I don't think it can be rebased into master without messing up the history since you seem to have '**Create SwitchScript.py**' which already exists in the main branch in your commits.  

What you should of done is rebased your first commit which was **'Initialized Machine List Page '** so that it would of attached itself to be the latest commit instead of adding the switch script commit to be over it and then adding commits on top of it. 

I probably recommend you make a new branch that has the most up to date main commits and then cherry pick each of your commits in order onto that branch and then squash your commits into only 1-2 commits to make them more legible. This shouldn't require you to copy and of your code over just git commands. Let me know if you want to get on call for help doing it

**Comment by erick576** [comment]
@JesseyH @ChandlerCabrera your changes had alot of annoying conflicts so I just did it for ur changes. Please refer to the PR I issued

**Comment by JesseyH** [comment]
Thanks for that @erick576! I'll take a look at the new PR you issued shortly

**Pull request closed without merging**
