### PR TITLE
Add machine model

### PR DESCRIPTION
**Pull request by erick576**
Please refer to instructions on #31 to see how to test model

### CODE REVIEW

**Review by digengill — APPROVED** [review]
Looks good

**Comment by Thanh2311** [comment]
are we not adding the relationship?

**Comment by erick576** [comment]
> are we not adding the relationship?

The user model needs to be defined to do that and we haven't created it yet. If we can agree on the fields we want the user model to have then I can just proceed to make it

**Review by elie0174 — APPROVED** [review]
lets figure out a user next meeting

**Comment by JesseyH** [comment]
@erick576 looks good, maybe let's discuss the User model on Wednesday's (Nov. 17) meeting? If anything let's get a skeleton of the model going.

**Review by JesseyH — APPROVED** [review]

**Pull request merged**
